### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by wangyu-ustc** [NVIDIA/RULER#75]
What are the required version of `nemo-toolkit` and `huggingface_hub`? I cannot get them correct

**Comment by hsiehjackson** [comment]
Here are the full installed packages in my recommended docker container. Hope this helps! 
```
absl-py                           2.0.0
accelerate                        1.0.0
addict                            2.4.0
aiohttp                           3.8.5
aiosignal                         1.3.1
alabaster                         1.0.0
aniso8601                         9.0.1
annotated-types                   0.5.0
antlr4-python3-runtime            4.9.3
anyio                             4.6.0
apex                              0.1
appdirs                           1.4.4
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
asciitree                         0.3.3
asttokens                         2.4.0
astunparse                        1.6.3
async-timeout                     4.0.3
attrdict                          2.0.1
attrs                             23.1.0
audioread                         3.0.1
babel                             2.16.0
backcall                          0.2.0
bcrypt                            4.2.0
beautifulsoup4                    4.12.2
black                             19.10b0
bleach                            6.0.0
blis                              0.7.11
boto3                             1.35.37
botocore                          1.35.37
braceexpand                       0.1.7
Brotli                            1.1.0
cachetools                        5.3.1
catalogue                         2.0.10
causal-conv1d                     1.4.0
cdifflib                          1.2.6
certifi                           2023.7.22
cffi                              1.16.0
charset-normalizer                3.2.0
click                             8.0.2
clip                              0.2.0
cloudpathlib                      0.15.1
cloudpickle                       2.2.1
cmake                             3.27.6
colorama                          0.4.6
comm                              0.1.4
confection                        0.1.3
contourpy                         1.1.1
cryptography                      43.0.1
cubinlinker                       0.3.0+2.gce0680b
cuda-python                       12.2.0rc5+5.g84845d1
cudf                              23.8.0
cugraph                           23.8.0
cugraph-dgl                       23.8.0
cugraph-service-client            23.8.0
cugraph-service-server            23.8.0
cuml                              23.8.0
cupy-cuda12x                      12.1.0
cycler                            0.12.1
cymem                             2.0.8
Cython                            3.0.3
cytoolz                           1.0.0
dask                              2023.7.1
dask-cuda                         23.8.0
dask-cudf                         23.8.0
datasets                          3.0.1
debugpy                           1.8.0
decorator                         5.1.1
defusedxml                        0.7.1
diffusers                         0.30.3
dill                              0.3.8
diskcache                         5.6.3
Distance                          0.1.3
distributed                       2023.7.1
distro                            1.9.0
dm-tree                           0.1.8
docker-pycreds                    0.4.0
docopt                            0.6.2
docutils                          0.21.2
editdistance                      0.8.1
einops                            0.7.0
einops-exts                       0.0.4
exceptiongroup                    1.1.3
execnet                           2.0.2
executing                         2.0.0
expecttest                        0.1.3
faiss-cpu                         1.8.0.post1
fastapi                           0.115.0
fasteners                         0.19
fastjsonschema                    2.18.1
fastrlock                         0.8.1
fasttext                          0.9.3
filelock                          3.12.4
flash-attn                        2.6.0.post1
Flask                             2.2.5
Flask-RESTful                     0.3.10
fonttools                         4.43.1
frozenlist                        1.4.0
fsspec                            2023.6.0
ftfy                              6.2.3
furl                              2.1.3
future                            1.0.0
g2p-en                            2.1.0
gast                              0.5.4
gdown                             5.2.0
gevent                            24.10.1
geventhttpclient                  2.0.2
gitdb                             4.0.11
GitPython                         3.1.43
google-ai-generativelanguage      0.6.10
google-api-core                   2.21.0
google-api-python-client          2.149.0
google-auth                       2.23.2
google-auth-httplib2              0.2.0
google-auth-oauthlib              0.4.6
google-generativeai               0.8.3
googleapis-common-protos          1.65.0
graphsurgeon                      0.4.6
greenlet                          3.1.1
grpcio                            1.66.2
grpcio-status                     1.62.3
h11                               0.14.0
h5py                              3.12.1
html2text                         2024.2.26
httpcore                          1.0.6
httplib2                          0.22.0
httptools                         0.6.1
httpx                             0.27.2
huggingface-hub                   0.23.4
hydra-core                        1.3.2
hypothesis                        5.35.1
idna                              3.4
ijson                             3.3.0
imageio                           2.35.1
imagesize                         1.4.1
importlib-metadata                6.8.0
inflect                           7.4.0
iniconfig                         2.0.0
intel-openmp                      2021.4.0
interegular                       0.3.3
intervaltree                      3.1.0
ipykernel                         6.25.2
ipython                           8.16.1
ipython-genutils                  0.2.0
ipywidgets                        8.1.5
isort                             5.13.2
itsdangerous                      2.2.0
jedi                              0.19.1
jieba                             0.42.1
Jinja2                            3.1.2
jiter                             0.6.1
jiwer                             2.5.2
jmespath                          1.0.1
joblib                            1.3.2
json5                             0.9.14
jsonschema                        4.19.1
jsonschema-specifications         2023.7.1
jupyter_client                    8.3.1
jupyter_core                      5.3.2
jupyter-tensorboard               0.2.0
jupyterlab                        2.3.2
jupyterlab-pygments               0.2.2
jupyterlab-server                 1.2.0
jupyterlab_widgets                3.0.13
jupytext                          1.15.2
kaldi-python-io                   1.2.2
kaldiio                           2.18.0
kiwisolver                        1.4.5
kornia                            0.7.3
kornia_rs                         0.1.5
langcodes                         3.3.0
lark                              1.2.2
latexcodec                        3.0.0
lazy_loader                       0.4
Levenshtein                       0.22.0
lhotse                            1.27.0
librosa                           0.10.2.post1
lightning-utilities               0.11.7
lilcom                            1.8.0
llvmlite                          0.40.1
lm-format-enforcer                0.10.3
locket                            1.0.0
loguru                            0.7.2
lxml                              5.3.0
mamba-ssm                         2.2.2
Markdown                          3.4.4
markdown-it-py                    3.0.0
markdown2                         2.5.1
MarkupSafe                        2.1.3
marshmallow                       3.22.0
matplotlib                        3.8.0
matplotlib-inline                 0.1.6
mdit-py-plugins                   0.4.0
mdurl                             0.1.2
megatron_core                     0.5.0
mistune                           3.0.2
mkl                               2021.1.1
mkl-devel                         2021.1.1
mkl-include                       2021.1.1
mock                              5.1.0
more-itertools                    10.5.0
mpmath                            1.3.0
msgpack                           1.0.5
multidict                         6.0.4
multiprocess                      0.70.16
murmurhash                        1.0.10
nbclient                          0.8.0
nbconvert                         7.9.2
nbformat                          5.9.2
nemo_text_processing              1.1.0
nemo_toolkit                      1.23.0
nerfacc                           0.5.3
nest-asyncio                      1.5.8
networkx                          2.6.3
ninja                             1.11.1.1
nltk                              3.9.1
notebook                          6.4.10
numba                             0.57.1+1.g5fba9aa8f
numcodecs                         0.13.1
numpy                             1.24.4
nvfuser                           0.0.20+gitunknown
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-dali-cuda120               1.30.0
nvidia-ml-py                      12.560.30
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.6.77
nvidia-nvtx-cu12                  12.1.105
nvidia-pyindex                    1.0.9
nvtx                              0.2.5
oauthlib                          3.2.2
omegaconf                         2.3.0
onnx                              1.14.0
open_clip_torch                   2.26.1
openai                            1.51.2
OpenCC                            1.1.6
opencv                            4.7.0
orderedmultidict                  1.0.1
outlines                          0.0.46
packaging                         23.1
pandas                            1.5.3
pandocfilters                     1.5.0
pangu                             4.0.6.1
parameterized                     0.9.0
paramiko                          3.5.0
parso                             0.8.3
partd                             1.4.0
pathspec                          0.12.1
pathy                             0.10.2
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            9.2.0
pip                               24.2
plac                              1.4.3
platformdirs                      3.11.0
pluggy                            1.3.0
ply                               3.11
polygraphy                        0.49.0
pooch                             1.7.0
portalocker                       2.10.1
preshed                           3.0.9
prettytable                       3.9.0
progress                          1.6
prometheus_client                 0.21.0
prometheus-fastapi-instrumentator 7.0.0
prompt-toolkit                    3.0.39
proto-plus                        1.24.0
protobuf                          4.24.4
psutil                            5.9.4
ptxcompiler                       0.8.1+1.g2cb1b35
ptyprocess                        0.7.0
pure-eval                         0.2.2
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyannote.core                     5.0.0
pyannote.database                 5.1.0
pyannote.metrics                  3.2.1
pyarrow                           17.0.0
pyasn1                            0.5.0
pyasn1-modules                    0.3.0
pybind11                          2.11.1
pybind11-global                   2.11.1
pybtex                            0.24.0
pybtex-docutils                   1.0.3
pycocotools                       2.0+nv0.7.3
pycountry                         24.6.1
pycparser                         2.21
pydantic                          2.4.2
pydantic_core                     2.10.1
pydub                             0.25.1
Pygments                          2.18.0
pylibcugraph                      23.8.0
pylibcugraphops                   23.8.0
pylibraft                         23.8.0
pyloudnorm                        0.1.1
PyMCubes                          0.1.6
PyNaCl                            1.5.0
pynini                            2.1.6.post1
pynvml                            11.4.1
pyparsing                         3.1.1
pypinyin                          0.53.0
pypinyin-dict                     0.8.0
PySocks                           1.7.1
pytest                            7.4.2
pytest-flakefinder                1.1.0
pytest-rerunfailures              12.0
pytest-runner                     6.0.1
pytest-shard                      0.1.2
pytest-xdist                      3.3.1
python-dateutil                   2.8.2
python-dotenv                     1.0.1
python-hostlist                   1.23.0
python-rapidjson                  1.20
pytorch-lightning                 2.0.7
pytorch-quantization              2.1.2
pytz                              2023.3
PyYAML                            6.0.1
pyzmq                             25.1.1
raft-dask                         23.8.0
rapidfuzz                         2.13.7
ray                               2.37.0
referencing                       0.30.2
regex                             2023.10.3
requests                          2.32.3
requests-oauthlib                 1.3.1
resampy                           0.4.2
rich                              13.9.2
rmm                               23.8.0
rotary-emb                        0.1
rouge-score                       0.1.2
rpds-py                           0.10.4
rsa                               4.9
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
s3transfer                        0.10.3
sacrebleu                         2.4.3
sacremoses                        0.1.1
safetensors                       0.4.5
scikit-learn                      1.2.0
scipy                             1.11.1
Send2Trash                        1.8.2
sentence-transformers             3.1.1
sentencepiece                     0.2.0
sentry-sdk                        2.16.0
setproctitle                      1.3.3
setuptools                        68.2.2
shellingham                       1.5.4
six                               1.16.0
smart-open                        6.4.0
smmap                             5.0.1
sniffio                           1.3.1
snowballstemmer                   2.2.0
sortedcontainers                  2.4.0
soundfile                         0.12.1
soupsieve                         2.5
sox                               1.5.0
soxr                              0.5.0.post1
spacy                             3.7.1
spacy-legacy                      3.0.12
spacy-loggers                     1.0.5
Sphinx                            8.0.2
sphinx-glpi-theme                 0.3
sphinxcontrib-applehelp           2.0.0
sphinxcontrib-bibtex              2.6.3
sphinxcontrib-devhelp             2.0.0
sphinxcontrib-htmlhelp            2.1.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              2.0.0
sphinxcontrib-serializinghtml     2.0.0
srsly                             2.4.8
sshtunnel                         0.4.0
sshtunnel-requests                0.1.3
stack-data                        0.6.3
starlette                         0.38.6
sympy                             1.12
tabulate                          0.9.0
taming-transformers               0.0.1
tbb                               2021.10.0
tblib                             2.0.0
tenacity                          9.0.0
tensorboard                       2.9.0
tensorboard-data-server           0.6.1
tensorboard-plugin-wit            1.8.1
tensorrt                          8.6.1
tensorstore                       0.1.45
termcolor                         2.5.0
terminado                         0.17.1
text-unidecode                    1.3
textdistance                      4.6.3
texterrors                        0.5.1
thinc                             8.2.1
threadpoolctl                     3.2.0
thriftpy2                         0.4.16
tiktoken                          0.8.0
timm                              1.0.9
tinycss2                          1.2.1
tokenizers                        0.19.1
toml                              0.10.2
tomli                             2.0.1
toolz                             0.12.0
torch                             2.4.0
torch-tensorrt                    0.0.0
torchdata                         0.7.0a0
torchdiffeq                       0.2.4
torchmetrics                      1.4.3
torchsde                          0.2.6
torchtext                         0.16.0a0
torchvision                       0.19.0
tornado                           6.3.3
tqdm                              4.66.5
traitlets                         5.9.0
trampoline                        0.1.2
transformer-engine                0.12.0+170797
transformers                      4.44.2
treelite                          3.2.0
treelite-runtime                  3.2.0
trimesh                           4.4.9
triton                            3.0.0
tritonclient                      2.50.0
typed-ast                         1.5.5
typeguard                         4.3.0
typer                             0.12.5
types-dataclasses                 0.6.6
typing_extensions                 4.12.2
ucx-py                            0.33.0
uff                               0.6.9
uritemplate                       4.1.1
urllib3                           2.2.3
uvicorn                           0.31.1
uvloop                            0.20.0
vllm                              0.5.4
vllm-flash-attn                   2.6.1
wandb                             0.18.3
wasabi                            1.1.2
watchfiles                        0.24.0
wcwidth                           0.2.13
weasel                            0.3.2
webdataset                        0.1.62
webencodings                      0.5.1
websockets                        13.1
Werkzeug                          3.0.0
wget                              3.2
wheel                             0.41.2
widgetsnbextension                4.0.13
wonderwords                       2.2.0
wrapt                             1.16.0
xdoctest                          1.0.2
xformers                          0.0.27.post2
xgboost                           1.7.5
xxhash                            3.5.0
yarl                              1.9.2
youtokentome                      1.0.6
zarr                              2.18.3
zict                              3.0.0
zipp                              3.16.2
zope.event                        5.0
zope.interface                    7.1.0
```

**Comment by AWolf81** [comment]
If you're getting an installation error for Cython during install of `youtokentome`. That is caused by build isolation of latest pip version.

The error message is:
```bash
$ pip install youtokentome
Collecting youtokentome
  Using cached youtokentome-1.0.6.tar.gz (86 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/alexander/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/home/alexander/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
        File "/home/alexander/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ivyvfcln/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-ivyvfcln/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ivyvfcln/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 512, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ivyvfcln/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'youtokentome' when getting requirements to build wheel
```

## Workaround
Either downgrade pip (e.g. `pip install pip==23.0.1`) or use the following command to install `youtokentome` - `pip install "cython<3.0" --no-build-isolation youtokentome`

I would use the second command to install and keep my current pip version. You might also need to install `wheel` before installing `youtokentome` as mentioned [here](https://github.com/VKCOM/YouTokenToMe/issues/107#issuecomment-1762142486)

## My env
Pip 25.3 and Python 3.10.14
